services:
  - type: worker
    name: trusty-dust-indexer
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npx ponder start --log-level=info
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PONDER_RPC_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PONDER_PORT
        value: "4000"